<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{4c756481-7ec3-4e41-a368-ed1e2246c441}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bBrowserStart: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AlarmSample();// Пример работы с авариями
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>